### ISSUE TITLE
Should "nan" be a dependency

### ISSUE THREAD

**Issue by tommoor** [fcanas/node-native-boilerplate#18]
Right now the nan module is a dev-only dependency, but upon shipping my module to NPM it seems as though nan is needed on the client machines too…

The [nan readme](https://github.com/nodejs/nan#usage) also seems to suggest that it should not be a dev dependency.

This repo is a great start for those that haven't written a native module before, it would be really excellent if it included more details on how to ship a working module too.

**Comment by fcanas** [comment]
That's an interesting finding. I'm not an expert on this at all. If you're confident that change is needed, I'd happily accept a pull request. Otherwise I'll try and research it and update some time in the next couple of months.

**Comment by tommoor** [comment]
The other example linked from the `nan` readme lists it as a dependency, https://github.com/encharm/nan-example-eol/blob/master/package.json#L27

I'll put a PR in shortly
