### ISSUE TITLE
Doesn't compile Ubuntu Node 0.12

### ISSUE THREAD

**Issue by yarax** [fcanas/node-native-boilerplate#5]
I'm using nvm for switching Node versions. Maybe it is a reason.

```
uname -a
Linux BAT-PC107 3.16.0-41-generic #57-Ubuntu SMP Thu Jun 18 08:44:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
npm i nan
npm WARN package.json @ No repository field.
npm WARN package.json @ No license field.
nan@2.0.0 node_modules/nan
npm run configure
> @ configure /tmp/node-native-boilerplate
> node-gyp configure

rkrivtsov@BAT-PC107:/tmp/node-native-boilerplate$ npm run build

> @ build /tmp/node-native-boilerplate
> node-gyp build

make: Entering directory '/tmp/node-native-boilerplate/build'
  CXX(target) Release/obj.target/NativeExtension/NativeExtension.o
../NativeExtension.cc: In function ‘void InitAll(v8::Handle<v8::Object>)’:
../NativeExtension.cc:14:16: error: ‘NanNew’ was not declared in this scope
   exports->Set(NanNew<String>("nothing"),
                ^
../NativeExtension.cc:14:29: error: expected primary-expression before ‘>’ token
   exports->Set(NanNew<String>("nothing"),
                             ^
../NativeExtension.cc:15:28: error: expected primary-expression before ‘>’ token
     NanNew<FunctionTemplate>(nothing)->GetFunction());
                            ^
../NativeExtension.cc:15:40: error: request for member ‘GetFunction’ in ‘nothing’, which is of non-class type ‘Nan::NAN_METHOD_RETURN_TYPE(Nan::NAN_METHOD_ARGS_TYPE) {aka void(const Nan::FunctionCallbackInfo<v8::Value>&)}’
```

**Comment by fcanas** [comment]
You incredibly helpfully included a ton of information :confetti_ball:  It looks like you directly installed Nan with `npm i nan` which led to Nan `2.0.0` getting installed. This boilerplate is currently compatible with Nan `1.x.x`, and is specified as such in `package.json`, though unhelfully not in the readme :8ball:.

You'll need to `rm -rf node_modules` to remove the incorrectly versioned dependencies, then run `npm i`.

```
$ rm -rf node_modules
$ npm i
$ npm run configure
$ npm run build
```

If nvm ran `npm i nan` _for_ you, then maybe that's some cause for concern. But I think this should work.

I'll need to update the readme with instructions to just run `npm i`.

Thanks for finding this issue! Let me know if this works for you, and for bringing Nan 2.0.0 to my attention. I should get around to updating the project to use it.

:cake:

**Comment by yarax** [comment]
Thank you for fast and comprehensive answer! It works

**Comment by fcanas** [comment]
Thanks for reporting the issue! :smile:  The goal of this repository is to be as accessible as possible. It's really important to me to get the documentation right. :memo: :white_check_mark: :+1:
